# Generated by Django 5.1.5 on 2025-01-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='producttoppings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='toppingsgroups',
            options={'managed': True},
        ),
    ]
